Add necessary files
ventilator-project/sensor_firmware pull request #1
Opened 2020-04-05 19:05 UTC by NalaGinrut

Add these files:

- .gitignore
- CONTRIBUTING.md

2020-04-05 19:28 UTC, cibomahto commented on CONTRIBUTING.md
> +[ch554_sdcc Issues](https://github.com/Blinkinlabs/ch554_sdcc/issues), start
Should reference the current project

2020-04-05 19:30 UTC, cibomahto commented on CONTRIBUTING.md
> +* Submit a pull request to the repository in the Blinkinlabs organization.
Change 'Blinkinlabs' to a generic 'this organization'

2020-04-05 19:32 UTC, cibomahto requested changes
Request a few name changes in the contributing document.

2020-04-06 01:53 UTC, NalaGinrut commented on CONTRIBUTING.md
> +[ch554_sdcc Issues](https://github.com/Blinkinlabs/ch554_sdcc/issues), start
done

2020-04-06 01:54 UTC, NalaGinrut commented on CONTRIBUTING.md
> +* Submit a pull request to the repository in the Blinkinlabs organization.
done

2020-04-06 05:03 UTC, cibomahto approved these changes

2020-04-06 05:03 UTC, merged